"""initial_schema

Revision ID: 07da6f3101a5
Revises: 
Create Date: 2026-04-02 19:23:53.444613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07da6f3101a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('critical_bins', sa.Boolean(), nullable=True),
    sa.Column('route_updates', sa.Boolean(), nullable=True),
    sa.Column('system_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_digest', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('compact_mode', sa.Boolean(), nullable=True),
    sa.Column('auto_refresh', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.add_column('routes', sa.Column('zone_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_routes_zone_id'), 'routes', ['zone_id'], unique=False)
    op.drop_constraint(op.f('routes_crew_id_fkey'), 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_crew_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'bins', ['bin_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_crew_id_fkey'), 'tasks', 'crews', ['crew_id'], ['id'])
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key(op.f('routes_crew_id_fkey'), 'routes', 'crews', ['crew_id'], ['id'])
    op.drop_index(op.f('ix_routes_zone_id'), table_name='routes')
    op.drop_column('routes', 'zone_id')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
